name: "Build and publish image with Nix"
on:
  push:
    branches: ["main"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Docker
        uses: docker/setup-docker-action@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: Build and publish images
        run: scripts/build_and_publish.sh
